containers:
  - name: backend
    image: "{{ .Values.backend.image }}:{{ .Values.backend.tag }}"
    imagePullPolicy: Always
    ports:
      - containerPort: {{ .Values.backend.port }}




containers:
  - name: frontend
    image: "{{ .Values.frontend.image }}:{{ .Values.frontend.tag }}"
    imagePullPolicy: Always
    ports:
      - containerPort: {{ .Values.frontend.port }}
