apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking-backend
  labels:
    app: banking-backend
spec:
  replicas: 6

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 2

  selector:
    matchLabels:
      app: banking-backend

  template:
    metadata:
      labels:
        app: banking-backend

    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image }}:{{ .Values.backend.tag }}"
          imagePullPolicy: Always

          ports:
            - containerPort: {{ .Values.backend.port }}

          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.backend.port }}
            initialDelaySeconds: 20
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.backend.port }}
            initialDelaySeconds: 40
            periodSeconds: 20

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking-frontend
  labels:
    app: banking-frontend
spec:
  replicas: 6

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 2

  selector:
    matchLabels:
      app: banking-frontend

  template:
    metadata:
      labels:
        app: banking-frontend

    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image }}:{{ .Values.frontend.tag }}"
          imagePullPolicy: Always

          ports:
            - containerPort: {{ .Values.frontend.port }}

          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
