apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: banking-backend
spec:
  selector:
    matchLabels:
      app: banking-backend

  endpoints:
  - port: http
    path: /actuator/prometheus
